# Generated by Django 2.0.5 on 2018-05-29 05:16

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='img',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='review/', verbose_name='автар'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='rights',
            field=models.SmallIntegerField(blank=True, db_index=True, default=None, verbose_name='балы'),
        ),
    ]
