# Generated by Django 2.0.5 on 2018-05-29 05:30

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180529_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='название')),
                ('img', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='study/', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'Преимущества обучения',
                'verbose_name_plural': 'Преимущества обучения',
                'ordering': ['name'],
            },
        ),
    ]
