# Generated by Django 2.0.5 on 2018-05-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_poststudy_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(default=34, verbose_name='описание'),
            preserve_default=False,
        ),
    ]
