# Generated by Django 2.0.5 on 2018-05-31 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_test_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionsCourseHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.CharField(blank=True, default=None, max_length=50, verbose_name='Условие')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Прайс курсов',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CourseHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, verbose_name='название курса')),
                ('language', models.CharField(blank=True, default=None, max_length=20, verbose_name='язык')),
                ('price', models.CharField(blank=True, default=None, help_text='с пробелом', max_length=20, verbose_name='цена за курс')),
                ('all_time', models.SmallIntegerField(blank=True, default=None, verbose_name='Общее время курса')),
                ('icon', models.CharField(blank=True, default=None, max_length=20, verbose_name='иконка')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Прайс курсов',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='conditionscoursehome',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.CourseHome', verbose_name='курс'),
        ),
    ]
