# Generated by Django 2.0.5 on 2018-05-31 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180531_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursehome',
            name='icon',
        ),
    ]
