# Generated by Django 2.0.5 on 2018-05-31 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_coursehome_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursehome',
            old_name='icon',
            new_name='icons',
        ),
    ]
