# Generated by Django 2.0.5 on 2018-05-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180531_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursehome',
            name='language',
        ),
        migrations.AddField(
            model_name='coursehome',
            name='descriptions',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='coursehome',
            name='all_time',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Общее время курса'),
        ),
    ]
