# Generated by Django 2.0.5 on 2018-05-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='название уровня')),
                ('balls', models.SmallIntegerField(blank=True, default=None, verbose_name='количество баллов')),
            ],
            options={
                'verbose_name': 'Уровень английского',
                'verbose_name_plural': 'Уровни английского',
                'ordering': ['name'],
            },
        ),
    ]
