# Generated by Django 2.0.5 on 2018-05-29 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_scoringscale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='house',
        ),
        migrations.AddField(
            model_name='order',
            name='level',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='orders.ScoringScale', verbose_name='уровень'),
            preserve_default=False,
        ),
    ]
